name: build
on:
  push:
    branches:
      - github_actions
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install nim
      run: |
        git clone https://github.com/nim-lang/Nim.git
        cd Nim
        chmod +x ./build_all.sh
        ./build_all.sh
    - name: Build darwintiler
      run: |
        make
